# sin version: innecesario desde Compose v2

volumes:
  mysql_data:

services:
  sqldb:
    image: mysql:5.7
    container_name: helper1-mysql
    ports:
      - "3307:3306" # Exponer MySQL al VPS en el puerto 3307
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=helper
      - MYSQL_USER=helper
      - MYSQL_PASSWORD=helper
      - MYSQL_ROOT_PASSWORD=helper
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  helper:
    image: raynorman/helper1:latest
    container_name: helper1-server
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=helper
      - DB_USERNAME=helper
      - DB_PASSWORD=helper
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=your_username
      - MAIL_PASSWORD=your_password
      - MAIL_ENCRYPTION=tls
      - APP_URL=https://seikaze.net.pe
      - ASSET_URL=https://seikaze.net.pe
      - APP_ENV=production
    depends_on:
      sqldb:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src:/var/www/html
      - ./uploads/comprobantes/abonos:/var/www/html/storage/app/public/comprobantes/abonos
      - ./uploads/clientes/fotos:/var/www/html/storage/app/public/clientes/fotos
      - ./uploads/comprobantes/yape:/var/www/html/storage/app/public/comprobantes/yape
      - ./uploads/comprobantes/efectivo:/var/www/html/storage/app/public/comprobantes/efectivo
      - ./uploads/departamentos:/var/www/html/storage/app/public/departamentos
      - ./bootstrap/cache:/var/www/html/bootstrap/cache

  nginx:
    image: nginx:alpine
    container_name: helper1-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - helper
    restart: unless-stopped
